version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.amazonaws:aws-java-sdk-bom
    versions:
    - "> 1.11.892"
  - dependency-name: com.diffplug.gradle.spotless
    versions:
    - "> 4.5.1"
  - dependency-name: io.spring.dependency-management
    versions:
    - "> 1.0.10.RELEASE"
  - dependency-name: junit:junit
    versions:
    - "> 4.13.1"
  - dependency-name: org.checkerframework:checker
    versions:
    - "> 3.6.1"
  - dependency-name: org.checkerframework:checker-qual
    versions:
    - "> 3.6.1"
  - dependency-name: org.checkerframework:framework-test
    versions:
    - "> 3.6.1"
  - dependency-name: org.projectlombok:lombok
    versions:
    - "> 1.18.16"
  - dependency-name: org.sosy-lab:java-smt
    versions:
    - "> 3.2.0"
  - dependency-name: org.springframework:spring-expression
    versions:
    - "> 5.3.0"
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-jre
